import StudioSelect from '@/components/StudioSelect';
import {useCallback,useEffect,useState} from 'react';
import {ArrowUpRight,CheckCircle2,CloudUpload,Copy,GitBranch,Globe,Loader2,RotateCcw} from 'lucide-react';
import {toast} from 'sonner';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import ExternalAccounts from './ExternalAccounts';
import {invoke,errorMessage} from '@/lib/sdk';
interface Job{id:string;kind:'publish'|'deploy';provider:string;version:number;status:string;stage:string;error:string;created:number;result:{url?:string;repository?:string;branch?:string;uploaded?:number;total?:number;site_id?:string;deploy_id?:string}}
interface DeliveryInfo{items:Job[];version:number;build_ready:boolean;deploy_blocker:string;connections:Record<string,boolean>}
const stages:Record<string,string>={queued:'等待开始',preparing:'准备交付文件',repository:'创建仓库',site:'创建公网站点',upload:'上传文件',processing:'平台正在处理',verifying:'检查公网访问',promoting:'切换线上版本',done:'已完成',error:'需要处理',interrupted:'进度已保留'};
export default function DeliveryPanel({projectId}:{projectId:number}){
  const [info,setInfo]=useState<DeliveryInfo|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const [provider,setProvider]=useState('github');const [name,setName]=useState(`atomforge-${projectId}`);const [existing,setExisting]=useState(false);const [repository,setRepository]=useState('');const [privateRepo,setPrivateRepo]=useState(true);
  const [tokens,setTokens]=useState<Record<string,string>>({});const [configured,setConfigured]=useState<Record<string,boolean>>({});
  const url=`/api/v1/delivery/projects/${projectId}`;
  const load=useCallback(async()=>{const r=await invoke<DeliveryInfo>({url});setInfo(r);setError('');},[url]);
  useEffect(()=>{let disposed=false;let timer:ReturnType<typeof setTimeout>;const refresh=async()=>{try{const r=await invoke<DeliveryInfo>({url});if(!disposed){setInfo(r);setError('');}}catch(e){if(!disposed)setError(errorMessage(e));}if(!disposed)timer=setTimeout(()=>void refresh(),4000);};void refresh();return()=>{disposed=true;clearTimeout(timer);};},[url]);
  useEffect(()=>{void invoke<Record<string,boolean>>({url:`/api/v1/connections/projects/${projectId}`}).then(r=>setConfigured(Object.fromEntries(['github','gitee','netlify'].map(p=>[p,!!r[p+'_token_configured']])))).catch(()=>{});},[projectId]);
  const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}};
  const active=info?.items.some(j=>['queued','running'].includes(j.status));
  const live=info?.items.find(j=>j.kind==='deploy'&&j.status==='done'&&j.result.url);
  return <section aria-label="源码发布与公网部署" className="space-y-5">
    <div className="rounded-2xl border bg-muted/30 p-5"><div className="flex items-center gap-2 text-primary"><Globe className="h-5 w-5"/><h3 className="font-semibold">让作品，真正上线</h3></div><p className="mt-2 text-xs leading-6 text-muted-foreground">源码可以交付到你的仓库，应用可以部署为独立公网网站。每次交付都会记录版本和结果。</p>{info&&<p className="mt-2 text-xs">当前 v{info.version} · {info.build_ready?'构建检查已通过':'部署前需完成构建检查'}</p>}</div>
    <ExternalAccounts redirect={`/p/${projectId}?delivery=1`}/>
    {live&&<div className="rounded-xl border border-primary/30 bg-primary/5 p-4"><p className="flex items-center gap-2 text-sm font-medium"><CheckCircle2 className="h-4 w-4 text-primary"/>公网应用已上线 · v{live.version}</p><a className="mt-2 flex items-center gap-2 break-all text-sm text-primary underline" href={live.result.url} target="_blank" rel="noreferrer">{live.result.url}<ArrowUpRight className="h-4 w-4 shrink-0"/></a><Button variant="ghost" size="sm" className="mt-2" onClick={()=>void navigator.clipboard.writeText(live.result.url!).then(()=>toast.success('公网链接已复制')).catch(()=>toast.error('复制失败，请手动复制链接'))}><Copy className="mr-1 h-3 w-3"/>复制链接</Button></div>}
    <div className="grid gap-4 lg:grid-cols-2">
      <section className="rounded-xl border p-4"><h3 className="flex items-center gap-2 text-sm font-semibold"><GitBranch className="h-4 w-4"/>发布源码</h3><p className="mb-4 mt-2 text-xs leading-5 text-muted-foreground">交付完整可运行工程，包含代码、依赖与启动说明。</p><label className="block text-xs">目标平台<StudioSelect aria-label="源码发布平台" className="mt-1" value={provider} onValueChange={setProvider} options={[{value:"github",label:"GitHub"},{value:"gitee",label:"Gitee"}]}/></label><label className="my-3 flex items-center gap-2 text-xs"><input type="checkbox" checked={existing} onChange={e=>setExisting(e.target.checked)}/>发布到已有仓库</label><label className="block text-xs">{existing?'仓库（owner/repo）':'新仓库名称'}<Input className="mt-1" value={existing?repository:name} onChange={e=>existing?setRepository(e.target.value):setName(e.target.value)} aria-label={existing?'仓库路径':'新仓库名称'}/></label>{!existing&&<label className="my-3 flex items-center gap-2 text-xs"><input type="checkbox" checked={privateRepo} onChange={e=>setPrivateRepo(e.target.checked)}/>私有仓库</label>}<p className="my-3 text-[11px] leading-5 text-muted-foreground">写入本次版本的独立分支，不覆盖默认分支。公开仓库中的源码可被所有人查看。</p><Button className="w-full" variant="outline" disabled={busy||active||!info?.connections?.[provider]||(existing?!repository:!name)} onClick={()=>void act(()=>invoke({url,method:'POST',data:{kind:'publish',provider,name:existing?'':name,repository:existing?repository:'',private:privateRepo}}))}>发布到 {provider==='github'?'GitHub':'Gitee'}</Button></section>
      <section className="flex flex-col rounded-xl border p-4"><h3 className="flex items-center gap-2 text-sm font-semibold"><CloudUpload className="h-4 w-4"/>部署公网应用</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">由 Netlify 托管，自动生成 HTTPS 公网链接。</p><ol className="my-5 space-y-4 text-xs text-muted-foreground">{['打包已验证的应用版本','上传并检查公网访问','更新正式地址，记录交付结果'].map((item,i)=><li key={item} className="flex gap-3"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-muted text-[10px]">{i+1}</span><span>{item}</span></li>)}</ol>{info?.deploy_blocker&&<p className="mb-3 text-xs leading-5 text-amber-700">{info.deploy_blocker}</p>}<p className="mb-4 mt-auto text-[11px] leading-5 text-muted-foreground">部署后，任何持有链接的人都能访问应用。使用你连接的 Netlify 账号及其部署额度。</p><Button className="w-full" disabled={busy||active||!info?.build_ready||!info?.connections?.netlify||!!info?.deploy_blocker} onClick={()=>void act(()=>invoke({url,method:'POST',data:{kind:'deploy',provider:'netlify'}}))}>{active?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<CloudUpload className="mr-2 h-4 w-4"/>}{!info?.connections?.netlify?'先连接 Netlify 账号':live?'更新公网版本':'部署并生成公网链接'}</Button></section>
    </div>
    {error&&<p role="alert" className="rounded-lg border border-destructive/20 bg-destructive/5 p-3 text-xs leading-6 text-destructive">{error}</p>}
    <details className="rounded-xl border p-4"><summary className="cursor-pointer text-xs font-medium">使用个人令牌连接（可选）</summary><p className="my-3 text-xs leading-5 text-muted-foreground">尚未配置平台 OAuth 应用时，可使用个人令牌发布和部署；第三方登录仍需 OAuth。密钥加密保存在当前项目，留空保留已有配置。</p><div className="space-y-3">{['github','gitee','netlify'].map(p=><label key={p} className="block text-xs">{p==='github'?'GitHub':p==='gitee'?'Gitee':'Netlify'} Token{configured[p]?' · 已配置':''}<Input aria-label={`${p} Token`} type="password" autoComplete="new-password" className="mt-1" value={tokens[p]||''} onChange={e=>setTokens({...tokens,[p]:e.target.value})}/></label>)}</div><p className="my-3 text-[11px] leading-5 text-muted-foreground">GitHub 需要仓库读写及创建权限，Gitee 需要 projects 权限；Netlify 令牌可在账号的 Applications 设置中创建。</p><Button size="sm" variant="outline" disabled={busy||!Object.values(tokens).some(v=>v.trim())} onClick={()=>void act(async()=>{await invoke({url:`/api/v1/connections/projects/${projectId}`,method:'PUT',data:Object.fromEntries(Object.entries(tokens).filter(([,v])=>v.trim()).map(([p,v])=>[p+'_token',v.trim()]))});setConfigured({...configured,...Object.fromEntries(Object.entries(tokens).filter(([,v])=>v.trim()).map(([p])=>[p,true]))});setTokens({});toast.success('发布凭据已保存');})}>保存发布凭据</Button></details>
    <section className="space-y-3"><h3 className="text-sm font-semibold">交付记录</h3>{!info?<p className="text-xs text-muted-foreground">正在读取交付状态…</p>:!info.items.length?<p className="rounded-xl border border-dashed p-5 text-xs text-muted-foreground">还没有交付记录。连接账号后，就可以发布第一个版本。</p>:info.items.map(j=><article key={j.id} className="rounded-xl border p-4"><div className="flex items-center justify-between gap-3"><span className="text-sm font-medium">{j.provider==='netlify'?'Netlify 部署':j.provider==='github'?'GitHub 源码':'Gitee 源码'} · v{j.version}</span><span className="flex items-center gap-1 text-xs text-muted-foreground">{['queued','running'].includes(j.status)&&<Loader2 className="h-3 w-3 animate-spin"/>}{stages[j.stage]||j.stage}</span></div><p className="mt-1 text-[10px] text-muted-foreground">{new Date(j.created*1000).toLocaleString()}</p>{j.result.uploaded&&j.status==='running'?<p className="mt-2 text-xs">已上传 {j.result.uploaded} / {j.result.total} 个文件</p>:null}{j.status==='done'&&j.result.url&&<a className="mt-2 inline-flex items-center gap-1 break-all text-xs text-primary underline" href={j.result.url} target="_blank" rel="noreferrer">{j.kind==='deploy'?'打开公网应用':'查看源码分支'}<ArrowUpRight className="h-3 w-3"/></a>}{j.error&&<p className="mt-2 text-xs leading-5 text-destructive">{j.error}</p>}{['error','interrupted'].includes(j.status)&&<Button size="sm" variant="outline" className="mt-3" disabled={busy||active} onClick={()=>void act(()=>invoke({url:`${url}/${j.id}/retry`,method:'POST'}))}><RotateCcw className="mr-1 h-3 w-3"/>{j.kind==='deploy'?'继续部署检查':'重新发布此版本'}</Button>}</article>)}</section>
  </section>;
}
