import {useState} from 'react';
import {ArrowUpRight,Check,Plus,Sparkles} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {STARTERS,type Starter} from '@/lib/starters';

function Cover({starter}:{starter:Starter}) {
  return <div aria-hidden="true" className="relative flex h-36 items-center justify-center overflow-hidden rounded-t-xl p-5" style={{background:`${starter.accent}12`}}>
    <div className="w-full max-w-[240px] rotate-[-3deg] rounded-lg border bg-background p-3 shadow-sm"><div className="mb-3 flex items-center gap-1"><span className="h-1.5 w-1.5 rounded-full" style={{background:starter.accent}}/><span className="h-1.5 w-1.5 rounded-full bg-muted"/><span className="ml-auto h-1 w-10 rounded bg-muted"/></div>
      {starter.id==='tasks'?<div className="space-y-2">{[true,false,false].map((done,i)=><div key={i} className="flex gap-2"><span className="h-3 w-3 rounded border" style={{background:done?starter.accent:'transparent'}}/><span className="mt-1 h-1.5 rounded bg-muted" style={{width:`${70-i*13}%`}}/></div>)}</div>:starter.id==='habits'?<div className="grid grid-cols-7 gap-1.5">{Array.from({length:14},(_,i)=><span key={i} className="aspect-square rounded" style={{background:i%4===0?'#e7edef':starter.accent,opacity:i%4===0?1:.6}}/>)}</div>:starter.id==='expenses'?<div className="flex h-14 items-end justify-between gap-2">{[40,70,55,90,65,80].map((h,i)=><span key={i} className="flex-1 rounded-t" style={{height:`${h}%`,background:starter.accent,opacity:.25+i*.12}}/>)}</div>:<div className="grid grid-cols-3 gap-2">{[0,1,2].map(i=><span key={i} className="aspect-square rounded" style={{background:`linear-gradient(${60+i*60}deg,${starter.accent}22,${starter.accent}${['77','44','99'][i]})`}}/>)}</div>}
    </div>
  </div>;
}

function InteractivePreview({id}:{id:string}) {
  const [tasks,setTasks]=useState([{id:1,text:'写下第一个想法',done:true},{id:2,text:'体验一个小功能',done:false},{id:3,text:'开始自己的项目',done:false}]);
  const [input,setInput]=useState('');const [filter,setFilter]=useState('全部');const [days,setDays]=useState([true,true,false,true,false,false,false]);
  const [expenses,setExpenses]=useState([{name:'早餐',amount:12},{name:'地铁',amount:4}]);const [amount,setAmount]=useState('');
  const [work,setWork]=useState<number|null>(null);
  if(id==='tasks')return <div className="space-y-4"><p className="font-semibold">今天，先完成一件小事</p><form className="flex gap-2" onSubmit={e=>{e.preventDefault();if(input.trim()){setTasks(items=>[...items,{id:Date.now(),text:input.trim(),done:false}]);setInput('');}}}><Input aria-label="示例任务名称" value={input} onChange={e=>setInput(e.target.value)} placeholder="添加一项任务" maxLength={80}/><Button size="icon" aria-label="添加示例任务" disabled={!input.trim()}><Plus className="h-4 w-4"/></Button></form><div className="flex gap-2">{['全部','待完成','已完成'].map(value=><Button key={value} size="sm" variant={filter===value?'secondary':'ghost'} onClick={()=>setFilter(value)}>{value}</Button>)}</div>{tasks.filter(t=>filter==='全部'||(filter==='已完成'?t.done:!t.done)).map(task=><label key={task.id} className="flex cursor-pointer items-center gap-3 rounded-lg border bg-background p-3 text-sm"><input type="checkbox" checked={task.done} onChange={()=>setTasks(items=>items.map(t=>t.id===task.id?{...t,done:!t.done}:t))}/><span className={task.done?'text-muted-foreground line-through':''}>{task.text}</span></label>)}<p className="text-xs text-muted-foreground">还有 {tasks.filter(t=>!t.done).length} 项待完成</p></div>;
  if(id==='habits')return <div className="space-y-5"><div><p className="font-semibold">每天阅读 15 分钟</p><p className="mt-1 text-xs text-muted-foreground">点击一天，试试完成与取消打卡。</p></div><div className="grid grid-cols-7 gap-1">{days.map((done,i)=><button key={i} aria-label={`周${'一二三四五六日'[i]}打卡`} aria-pressed={done} onClick={()=>setDays(values=>values.map((v,n)=>n===i?!v:v))} className={`flex flex-col items-center gap-3 rounded-lg border py-3 text-xs ${done?'border-emerald-500 bg-emerald-50 text-emerald-700':'bg-background'}`}><span>{'一二三四五六日'[i]}</span>{done?<Check className="h-4 w-4"/>:<span className="h-4 w-4 rounded-full border"/>}</button>)}</div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-emerald-500 transition-all" style={{width:`${days.filter(Boolean).length/7*100}%`}}/></div><p className="text-sm">本周已完成 {days.filter(Boolean).length} / 7 天</p></div>;
  if(id==='expenses')return <div className="space-y-4"><p className="text-xs text-muted-foreground">示例支出合计</p><p className="text-3xl font-semibold">¥ {expenses.reduce((sum,item)=>sum+item.amount,0).toFixed(2)}</p><form className="grid grid-cols-2 gap-2" onSubmit={e=>{e.preventDefault();if(input.trim()&&Number(amount)>0&&Number.isFinite(Number(amount))){setExpenses(items=>[...items,{name:input.trim(),amount:Number(amount)}]);setInput('');setAmount('');}}}><Input aria-label="示例支出名称" value={input} onChange={e=>setInput(e.target.value)} placeholder="支出名称" maxLength={40}/><Input aria-label="示例支出金额" type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="金额"/><Button className="col-span-2" disabled={!input.trim()||!(Number(amount)>0)}>记一笔</Button></form>{expenses.map((item,i)=><div key={i} className="flex justify-between border-b py-2 text-sm"><span>{item.name}</span><span>¥ {item.amount.toFixed(2)}</span></div>)}</div>;
  const works=[{title:'品牌视觉',category:'设计'},{title:'周末随拍',category:'摄影'},{title:'产品界面',category:'设计'}];
  return <div className="space-y-4"><p className="font-semibold">你好，我是林。用作品介绍自己。</p><div className="flex gap-2">{['全部','设计','摄影'].map(category=><Button key={category} size="sm" variant={filter===category?'secondary':'ghost'} onClick={()=>{setFilter(category);setWork(null);}}>{category}</Button>)}</div><div className="grid grid-cols-2 gap-3">{works.map((item,i)=>filter==='全部'||filter===item.category?<button key={item.title} onClick={()=>setWork(i)} className="rounded-lg border bg-background p-2 text-left"><div className="mb-2 flex h-20 items-center justify-center rounded text-3xl font-semibold text-white" style={{background:['#956499','#557487','#ba8b63'][i]}}>{['Aa','◒','▤'][i]}</div><p className="text-xs">{item.title}</p></button>:null)}</div>{work!==null&&<div role="status" className="rounded-lg bg-muted p-3 text-sm"><strong>{works[work].title}</strong><p className="mt-1 text-xs text-muted-foreground">这里可以展示创作背景、过程和作品细节。</p></div>}</div>;
}

export default function StarterGallery({onUse,disabled}:{onUse:(prompt:string)=>void;disabled:boolean}){
  const [category,setCategory]=useState('全部');const [selected,setSelected]=useState<Starter|null>(null);const [prompt,setPrompt]=useState('');
  return <section id="inspiration" aria-label="灵感库" className="scroll-mt-20 border-t pt-8">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-lg font-semibold">从一个灵感开始</h2><p className="mt-1 text-sm text-muted-foreground">先试一试交互，再把需求改成自己的。选择示例不会启动生成。</p></div><div className="flex flex-wrap gap-1" aria-label="灵感分类">{['全部','效率工具','生活管理','个人展示'].map(value=><Button key={value} size="sm" variant={value===category?'secondary':'ghost'} aria-pressed={value===category} onClick={()=>setCategory(value)}>{value}</Button>)}</div></div>
    <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{STARTERS.filter(s=>category==='全部'||s.category===category).map(starter=><button key={starter.id} type="button" disabled={disabled} aria-label={`体验${starter.title}`} onClick={()=>{setSelected(starter);setPrompt(starter.prompt);}} className="group overflow-hidden rounded-xl border bg-card text-left transition-shadow hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><Cover starter={starter}/><div className="p-4"><p className="flex items-center justify-between text-sm font-semibold">{starter.title}<ArrowUpRight className="h-4 w-4 text-muted-foreground group-hover:text-primary"/></p><p className="mt-2 min-h-10 text-xs leading-5 text-muted-foreground">{starter.description}</p><p className="mt-3 text-[10px] text-muted-foreground">{starter.features.join(' · ')}</p></div></button>)}</div>
    <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="max-h-[90dvh] max-w-4xl overflow-auto"><DialogHeader><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>这是可操作的交互示例。试用数据只在本次预览中保留；正式应用将按右侧需求重新生成。</DialogDescription></DialogHeader>{selected&&<div className="grid gap-5 md:grid-cols-2"><div className="rounded-xl border bg-muted/20 p-4"><p className="mb-4 text-[11px] text-muted-foreground">交互预览 · 可以直接操作</p><InteractivePreview key={selected.id} id={selected.id}/></div><div className="flex flex-col gap-3"><label htmlFor="starter-prompt" className="text-sm font-medium">把它改成你的需求</label><Textarea id="starter-prompt" aria-label="示例生成需求" value={prompt} onChange={e=>setPrompt(e.target.value)} className="min-h-56 flex-1 text-sm leading-6" maxLength={3500}/><p className="text-xs leading-5 text-muted-foreground">填入首页后，还可以选择工程师或团队模式，再开始创建。</p><Button disabled={disabled||prompt.trim().length<4} onClick={()=>{onUse(prompt.trim());setSelected(null);}}><Sparkles className="mr-2 h-4 w-4"/>使用这份需求</Button></div></div>}</DialogContent></Dialog>
  </section>;
}
