pid /tmp/nginx.pid;
error_log /dev/stderr warn;
events { worker_connections 128; }
http {
  resolver 127.0.0.11 valid=10s ipv6=off;
  access_log off;
  client_body_temp_path /tmp/client;
  proxy_temp_path /tmp/proxy;
  fastcgi_temp_path /tmp/fastcgi;
  uwsgi_temp_path /tmp/uwsgi;
  scgi_temp_path /tmp/scgi;
  server {
    listen 8001;
    client_max_body_size 2m;
    location / {
      set $verification_upstream http://runner:8001;
      proxy_pass $verification_upstream;
      proxy_read_timeout 75s;
      proxy_buffering off;
    }
  }
}
