"""auto update

Revision ID: 64d7e70d15b6
Revises: 0703b62313a9
Create Date: 2026-09-11 05:23:07.187366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d7e70d15b6'
down_revision: Union[str, Sequence[str], None] = '0703b62313a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('af_users', sa.Column('email_verified_at', sa.String(), nullable=True))
    op.add_column('af_users', sa.Column('password_changed_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('af_users', 'password_changed_at')
    op.drop_column('af_users', 'email_verified_at')
    # ### end Alembic commands ###