"""auto update

Revision ID: 80d920d8a4c7
Revises: 64d7e70d15b6
Create Date: 2026-09-11 06:40:51.207929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80d920d8a4c7'
down_revision: Union[str, Sequence[str], None] = '64d7e70d15b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_af_email_tokens_af_user_id'), table_name='af_email_tokens')
    op.drop_index(op.f('ix_af_email_tokens_id'), table_name='af_email_tokens')
    op.drop_table('af_email_tokens')
    op.drop_column('af_users', 'email_verified_at')
    op.drop_column('af_users', 'password_changed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('af_users', sa.Column('password_changed_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('af_users', sa.Column('email_verified_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('af_email_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('af_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('used_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('request_ip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('delivery_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('af_email_tokens_pkey'))
    )
    op.create_index(op.f('ix_af_email_tokens_id'), 'af_email_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_af_email_tokens_af_user_id'), 'af_email_tokens', ['af_user_id'], unique=False)
    # ### end Alembic commands ###